# Generated by Django 4.1 on 2022-10-16 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DeepDive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timespent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timespent', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BiggestGoals',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('goal', models.CharField(max_length=64)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('dislike', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='Fears',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('fear', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('like', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='PersonalityTraits',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('openess', models.IntegerField(default=0)),
                ('conscientiousness', models.IntegerField(default=0)),
                ('extroversion', models.IntegerField(default=0)),
                ('agreableness', models.IntegerField(default=0)),
                ('neuroticism', models.IntegerField(default=0)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='SelfRealizations',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('selfrealization', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='Strengths',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('strength', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('value', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='Weaknesses',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('weakness', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
    ]
