# Generated by Django 4.1 on 2022-10-17 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeepDive', '0002_timespent_userinputs_biggestgoals_dislikes_fears_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charactertrait', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CharismaTips',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('tip', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='Comrades',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('name', models.CharField(max_length=32)),
                ('service', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='DosAndDonts',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('point', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('exercise', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='FindingLove',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('thought', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='GoldenRules',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('rule', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='LeadershipTips',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('leading_tip', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='Meditions',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('meditation', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='ObservationStratedy',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('stratedy', models.CharField(max_length=128)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=32)),
                ('finished_reading', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Romances',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('romance', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=32)),
                ('finished_learning', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SocialDare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dare', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ThemesOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TraitsUpgrading',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('trait', models.CharField(max_length=32)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='Visualizatoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(max_length=32)),
                ('finished_watching', models.BooleanField(default=False)),
            ],
        ),
    ]
