# Generated by Django 4.1 on 2022-10-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeepDive', '0003_charactertraits_charismatips_comrades_dosanddonts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalitytraits',
            old_name='openess',
            new_name='openness',
        ),
    ]
