# Generated by Django 4.1 on 2022-10-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeepDive', '0004_rename_openess_personalitytraits_openness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalitytraits',
            old_name='agreableness',
            new_name='agreeableness',
        ),
    ]
