# Generated by Django 4.1 on 2022-10-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeepDive', '0006_delete_readinglist_delete_skilllist_delete_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('book', models.CharField(max_length=32)),
                ('finished_reading', models.BooleanField(default=False)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('skill', models.CharField(max_length=32)),
                ('finished_learning', models.BooleanField(default=False)),
            ],
            bases=('DeepDive.userinputs',),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('userinputs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeepDive.userinputs')),
                ('show', models.CharField(max_length=32)),
                ('finished_watching', models.BooleanField(default=False)),
            ],
            bases=('DeepDive.userinputs',),
        ),
    ]
