# Generated by Django 4.1 on 2022-10-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeepDive', '0007_readinglist_skilllist_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterTraits',
        ),
        migrations.RemoveField(
            model_name='charismatips',
            name='userinputs_ptr',
        ),
        migrations.RemoveField(
            model_name='comrades',
            name='userinputs_ptr',
        ),
        migrations.DeleteModel(
            name='Emotions',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='userinputs_ptr',
        ),
        migrations.RemoveField(
            model_name='leadershiptips',
            name='userinputs_ptr',
        ),
        migrations.RemoveField(
            model_name='meditions',
            name='userinputs_ptr',
        ),
        migrations.RemoveField(
            model_name='observationstratedy',
            name='userinputs_ptr',
        ),
        migrations.DeleteModel(
            name='SocialDare',
        ),
        migrations.DeleteModel(
            name='ThemesOfTheDay',
        ),
        migrations.DeleteModel(
            name='Visualizatoins',
        ),
        migrations.DeleteModel(
            name='CharismaTips',
        ),
        migrations.DeleteModel(
            name='Comrades',
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
        migrations.DeleteModel(
            name='LeadershipTips',
        ),
        migrations.DeleteModel(
            name='Meditions',
        ),
        migrations.DeleteModel(
            name='ObservationStratedy',
        ),
    ]
